version: '3.8'

services:
  app:
    container_name: app-php
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./challenge_foco:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: app-web-nginx
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./challenge_foco:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network
    
  # postgresql:
  #   image: postgres:16.2
  #   container_name: app-postgresql
  #   environment:
  #       POSTGRES_DB: ${DB_DATABASE:-challenge_db}
  #       POSTGRES_USER: ${DB_USERNAME:-user_db_app}
  #       POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
  #       PGDATA: /data/postgres
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   ports:
  #       - "${FORWARD_DB_PORT:-5432}:5432"
  #   expose:
  #       - 5432
  #   networks:
  #       - app-network
  #   restart: unless-stopped

  db:
    platform: linux/amd64
    image: mysql:8.0.39
    container_name: app-db-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: user_db_app
      MYSQL_PASSWORD: password
    networks:
      - app-network
    volumes:
      # - ./docker/mysql/challenge_db.sql:/docker-entrypoint-initdb.d/challenge_db.sql 
      - ./database_data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    container_name: app-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - app-network
    environment:
      PMA_HOST: app-db-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: db_password

    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  database-data:
    driver: local
